### ISSUE TITLE
Document correct use of nc_inq_att() and nc_get_att() on new provenance attributes

### ISSUE THREAD

**Issue by czender** [Unidata/netcdf-c#265]
> Please provide as much of the following information as you can, as applicable to the issue being reported.  Naturally, not all information is relevant to every issue, but the more information we have to start, the better!

### Environment Information

> Feel free to skip this if the issue is related to documentation, a feature request, or general discussion.

* What platform are you using? (please provide specific distribution/version in summary)
  * [ ] Linux
  * [ ] Windows
  * [ ] OSX
  * [ ] Other
  * [ ] NA
* 32 and/or 64 bit?
  * [ ] 32-bit
  * [ ] 64-bit
* What build system are you using?
  * [ ] autotools (`configure`)
  * [ ] cmake
* Can you provide a sample netCDF file or `C` code to recreate the issue?
  * [ ] Yes (please attach to this issue, thank you!)
  * [ ] No
  * [ ] Not at this time

### Summary of Issue

Document correct use of nc_inq_att() and nc_get_att() on new provenance attributes
### Steps to reproduce the behavior

Question 1: is nc_inq_att (supposed to be) supported for these attributes? 
nc_inq_att() for "_NCProperties" returns type==NC_NAT or random integer, and size is random for files without _NCProperties.
NCO handles this by setting type to NC_CHAR and using size.
nc_inq_att() for "_IsNetcdf4" and "_SuperblockVersion" returns random random type and size too.
NCO handles this by setting type to NC_INT and setting size to 1.
Question 2: if nc_inq_att() is not supported for these attributes, what are the recommendations for picking type and size of each?
Question 3: have these provenance attributes been tested on HDF4 and HDF5 files using older HDF libraries? They seem to be causing crashes (see previous issue) even when these provenance attributes are not queried.

**Comment by DennisHeimbigner** [comment]
Charlie- I have a github branch (provfix) that I believe should
fix this issue. If you want, you can fetch that branch and try it.

**Comment by czender** [comment]
Thanks, Dennis. If someone pings me when it's merged to master I'll test it then.

**Comment by WardF** [comment]
@czender The fix is in `master` now, would you mind testing? Thanks!

**Comment by czender** [comment]
first three lines of  configure output are:

> configure: netCDF 4.4.1-development
> date: invalid date '@'
> checking build system type... x86_64-unknown-linux-gnu

and netCDF library date string is not updating in NCO.

the provenance patches do seem to work as intended.

bad news is the provenance feature (presumably) still breaks NCO reading HDF4 files, and still breaks NCO and ncdump reading HDF5 files.

**Comment by WardF** [comment]
I notice that `invalid date @` thing as well, now.  I'll try to sort out what happened with that.  

When I run the NCO tests using the netCDF-C development library, I'm not seeing any failures (in NCO's regular `make check`, at least).  @DennisHeimbigner , should the patch you provided mitigate the failures Charlie is seeing/expects to see? I confess I haven't examined the details of the fix at this point.

**Comment by czender** [comment]
NCO does not include any regression tests on any HDF4 or HDF5 files. I ran these tests by hand. As we discussed at AGU, Ward, the "real" NCO regression tests are executed with "make test" not "make check" (which does only a simple check). Try ncdump on 
[this](http://dust.ess.uci.edu/tmp/tdset.h5). It may not have been clear, but I submitted two bug reports on provenance features. The API now works, that's fixed. But it breaks access to HDF4 and HDF5 files, at least with the libhdf I link to. Same behavior on up-to-date MacOSX and FC23.

**Comment by WardF** [comment]
I remembered that there were two different commands for tests, but hadn't had a chance to test the `make test` bit yet.  I've got a fix for the date issue in the pipeline, which will be merged into `master` as soon as travis-ci is finished.  I'll take a look at the details of this issue as soon as I can, certainly before the next RC.

**Comment by DennisHeimbigner** [comment]
Yes, those fixes should have solved the problems.
Oh well, back to the drawing board.
Charlie- is there any info you can provide about the failures
you are seeing?
=Dennis Heimbigner

**Comment by czender** [comment]
Can you try to reproduce (and fix) the behavior of ncdump on the test file I linked to above?
```
zender@frazil:/data/zender/hdf$ ncdump tdset.h5
netcdf tdset {
dimensions:
	phony_dim_0 = 10 ;
	phony_dim_1 = 20 ;
	phony_dim_2 = 30 ;
variables:
NetCDF: Invalid dimension ID or name
Location: file ncdump.c; line 1697
	int dset1(
```

**Comment by DennisHeimbigner** [comment]
So, the problem has to do with the recently added use of hashing to speed up
searched. In nc4hdf.c, special dimensions are sometimes created called 'phony_dim_N'.
When created, these dimensions needed to have their hash field set.

**Comment by DennisHeimbigner** [comment]
Fixed in pull request #270

**Comment by czender** [comment]
Great! let me know when it's merged to master and i'll test it...

**Comment by WardF** [comment]
It has been merged!

**Comment by czender** [comment]
ncdump now works for me, and NCO still breaks on basically all HDF4 and HDF5 files, with messages like those below. NCO only uses standard netCDF API calls. Sometime between February and now these operations break. It is important to note that the HDF errors/warnings about _NCProperties occur whether or not NCO queries that attribute (!).  

```
zender@frazil:~/nco$ ncdump -h -s ${DATA}/hdf/tdset.h5
netcdf tdset {
dimensions:
	phony_dim_0 = 10 ;
	phony_dim_1 = 20 ;
	phony_dim_2 = 30 ;
variables:
	int dset1(phony_dim_0, phony_dim_1) ;
		dset1:_Storage = "contiguous" ;
		dset1:_Endianness = "big" ;
		dset1:_NoFill = "true" ;
	double dset2(phony_dim_2, phony_dim_1) ;
		dset2:_Storage = "contiguous" ;
		dset2:_Endianness = "big" ;
		dset2:_NoFill = "true" ;

// global attributes:
		:_SuperblockVersion = 0 ;
		:_IsNetcdf4 = 0 ;
		:_Format = "netCDF-4" ;
}
zender@frazil:~/nco$ ncks -M --hdn --cdl ${DATA}/hdf/tdset.h5
HDF5-DIAG: Error detected in HDF5 (1.8.15-patch1) thread 0:
  #000: ../../src/H5Adeprec.c line 243 in H5Aopen_name(): can't open attribute: '_NCProperties'
    major: Attribute
    minor: Can't open object
  #001: ../../src/H5Aint.c line 451 in H5A_open_by_name(): unable to load attribute info from object header
    major: Attribute
    minor: Unable to initialize object
  #002: ../../src/H5Oattribute.c line 537 in H5O_attr_open_by_name(): can't locate attribute: '_NCProperties'
    major: Attribute
    minor: Object not found
HDF5-DIAG: Error detected in HDF5 (1.8.15-patch1) thread 0:
  #000: ../../src/H5Adeprec.c line 243 in H5Aopen_name(): can't open attribute: '_NCProperties'
    major: Attribute
    minor: Can't open object
  #001: ../../src/H5Aint.c line 451 in H5A_open_by_name(): unable to load attribute info from object header
    major: Attribute
    minor: Unable to initialize object
  #002: ../../src/H5Oattribute.c line 537 in H5O_attr_open_by_name(): can't locate attribute: '_NCProperties'
    major: Attribute
    minor: Object not found
netcdf tdset {
  dimensions:
    phony_dim_0 = 10 ;
    phony_dim_1 = 20 ;
    phony_dim_2 = 30 ;

  variables:
HDF5-DIAG: Error detected in HDF5 (1.8.15-patch1) thread 0:
  #000: ../../src/H5Adeprec.c line 243 in H5Aopen_name(): can't open attribute: '_NCProperties'
    major: Attribute
    minor: Can't open object
  #001: ../../src/H5Aint.c line 451 in H5A_open_by_name(): unable to load attribute info from object header
    major: Attribute
    minor: Unable to initialize object
  #002: ../../src/H5Oattribute.c line 537 in H5O_attr_open_by_name(): can't locate attribute: '_NCProperties'
    major: Attribute
    minor: Object not found
HDF5-DIAG: Error detected in HDF5 (1.8.15-patch1) thread 0:
  #000: ../../src/H5Adeprec.c line 243 in H5Aopen_name(): can't open attribute: '_NCProperties'
    major: Attribute
    minor: Can't open object
  #001: ../../src/H5Aint.c line 451 in H5A_open_by_name(): unable to load attribute info from object header
    major: Attribute
    minor: Unable to initialize object
  #002: ../../src/H5Oattribute.c line 537 in H5O_attr_open_by_name(): can't locate attribute: '_NCProperties'
    major: Attribute
    minor: Object not found
    int dset1(phony_dim_0,phony_dim_1) ;
      dset1:_NOFILL = 1 ;
      dset1:_Storage = "contiguous" ;
      dset1:_Endianness = "big" ;

HDF5-DIAG: Error detected in HDF5 (1.8.15-patch1) thread 0:
  #000: ../../src/H5Adeprec.c line 243 in H5Aopen_name(): can't open attribute: '_NCProperties'
    major: Attribute
    minor: Can't open object
  #001: ../../src/H5Aint.c line 451 in H5A_open_by_name(): unable to load attribute info from object header
    major: Attribute
    minor: Unable to initialize object
  #002: ../../src/H5Oattribute.c line 537 in H5O_attr_open_by_name(): can't locate attribute: '_NCProperties'
    major: Attribute
    minor: Object not found
HDF5-DIAG: Error detected in HDF5 (1.8.15-patch1) thread 0:
  #000: ../../src/H5Adeprec.c line 243 in H5Aopen_name(): can't open attribute: '_NCProperties'
    major: Attribute
    minor: Can't open object
  #001: ../../src/H5Aint.c line 451 in H5A_open_by_name(): unable to load attribute info from object header
    major: Attribute
    minor: Unable to initialize object
  #002: ../../src/H5Oattribute.c line 537 in H5O_attr_open_by_name(): can't locate attribute: '_NCProperties'
    major: Attribute
    minor: Object not found
    double dset2(phony_dim_2,phony_dim_1) ;
      dset2:_NOFILL = 1 ;
      dset2:_Storage = "contiguous" ;

  // global attributes:
    :_Format = "netCDF-4" ;
    :_SOURCE_FORMAT = "NC_FORMATX_HDF5" ;
    :_IsNetcdf4 = 0 ;
    :_SuperblockVersion = 0 ;

} // group /
```

**Comment by DennisHeimbigner** [comment]
This may be an artifact of the fact that as part of its processing,
netcdf checks to see if e.g. _NCProperties is already defined in a file.
In that test, it expects hdf5 library to report an error indicating that the property
does not exist (which, of course it will not in a pure hdf5 file).
It looks like --enable-logging is set, correct?. It also looks like the ncdump
is completing correctly; am I misreading it? 

So, I am not sure that there is an actual error here. Perhaps I am using the wrong hdf5 calls
to test for attribute existence so that failure to find an attribute will not cause the output you see.
I will look at the HDF5 API again to see if there is a way to deal with this.

**Comment by czender** [comment]
Ahh. I hadn't noticed it was actually completing correctly because of the noise from all the HDF5 warnings. Yes, i configured with --enable-logging. A way to quiet the HDF warnings from acceptable error returns (e.g., when _NCProperties does not exist) would be welcome.

**Comment by WardF** [comment]
I've merged @DennisHeimbigner 's latest fix into `master`; if it quiets the messages, I'll go ahead and close out this issue.  Thanks both!

**Comment by czender** [comment]
Unfortunately the latest snapshot does not solve the problem with HDF warning when logging is turned-on (see below). This makes enable-logging untenable, at least with NCO, because the messages are so noisy.

```
zender@frazil:/data/zender/hdf$ ncdump tdset.h5 > ~/foo 2>&1
zender@frazil:/data/zender/hdf$ more ~/foo
netcdf tdset {
dimensions:
        phony_dim_0 = 10 ;
        phony_dim_1 = 20 ;
        phony_dim_2 = 30 ;
variables:
        int dset1(phony_dim_0, phony_dim_1) ;
        double dset2(phony_dim_2, phony_dim_1) ;
HDF5-DIAG: Error detected in HDF5 (1.8.15-patch1) thread 0:
  #000: ../../src/H5Adeprec.c line 243 in H5Aopen_name(): can't open attribute: '_NCProperties'
    major: Attribute
    minor: Can't open object
  #001: ../../src/H5Aint.c line 451 in H5A_open_by_name(): unable to load attribute info from object header
    major: Attribute
    minor: Unable to initialize object
  #002: ../../src/H5Oattribute.c line 537 in H5O_attr_open_by_name(): can't locate attribute: '_NCProperties'
    major: Attribute
    minor: Object not found
HDF5-DIAG: Error detected in HDF5 (1.8.15-patch1) thread 0:
  #000: ../../src/H5Adeprec.c line 243 in H5Aopen_name(): can't open attribute: '_NCProperties'
    major: Attribute
    minor: Can't open object
  #001: ../../src/H5Aint.c line 451 in H5A_open_by_name(): unable to load attribute info from object header
    major: Attribute
    minor: Unable to initialize object
  #002: ../../src/H5Oattribute.c line 537 in H5O_attr_open_by_name(): can't locate attribute: '_NCProperties'
    major: Attribute
    minor: Object not found
HDF5-DIAG: Error detected in HDF5 (1.8.15-patch1) thread 0:
  #000: ../../src/H5Adeprec.c line 243 in H5Aopen_name(): can't open attribute: '_NCProperties'
    major: Attribute
    minor: Can't open object
  #001: ../../src/H5Aint.c line 451 in H5A_open_by_name(): unable to load attribute info from object header
    major: Attribute
    minor: Unable to initialize object
  #002: ../../src/H5Oattribute.c line 537 in H5O_attr_open_by_name(): can't locate attribute: '_NCProperties'
    major: Attribute
    minor: Object not found
data:

 dset1 =
  0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
...
```

**Comment by DennisHeimbigner** [comment]
It looks to me like the relevant pull request
(https://github.com/Unidata/netcdf-c/pull/272)
has not yet been merged. I think Ward
is still testing it using visual studio.

**Comment by WardF** [comment]
.... yes, that would help wouldn't it? I did test everything at least, and I *thought* I had merged it.... Ok. Trying that again. I've got NCO open in a different window, so I can check and see if the behavior changes after merging.

**Comment by WardF** [comment]
From my testing this appears resolved.  Nominating to close unless I hear differently :).

**Comment by WardF** [comment]
Adding labels because better late than never.
