### ISSUE TITLE
'test_common.sh': No such file or directory

### ISSUE THREAD

**Issue by wkliao** [Unidata/netcdf-c#413]
When running configure command (vpath build), I got the following message.
mv: cannot stat `netcdf-c/test_common.sh': No such file or directory

I believe the cause comes from
https://github.com/Unidata/netcdf-c/blob/master/configure.ac#L1492

**Comment by WardF** [comment]
Thanks; I'll correct!

**Comment by WardF** [comment]
@wkliao How did you invoke configure? I'm running the following series of commands

    $ mkdir tmp && cd tmp
    $ ~/Desktop/gitprojects/netcdf-c/configure 
    $ make && make check

I am not encountering the error you have reported.  I can envision a couple different ways in which  test_common.sh fails to be generated, which would cause this issue.  I'm not certain why we're using `sed` instead of `AC_CONFIG_FILES`, but I will investigate that.

**Comment by wkliao** [comment]
I did the same. That message appeared during configure time, close to the end.
I think you can safely remove line 1492, because file test_common.sh has already been generated at line 1447 under folder ${abs_top_builddir}

1447 sed -e "s|@TOPSRCDIR@|${abs_top_srcdir}|" -e "s|@TOPBUILDDIR@|${abs_top_builddir}|" <${abs_top_srcdir}/test_common.in >${abs_top_builddir}/test_common.sh

1492    mv -f ${abs_top_srcdir}/test_common.sh ${abs_top_builddir}/test_common.sh

**Comment by WardF** [comment]
Fixed in a pending commit.

**Comment by wkliao** [comment]
The fix 6da1539 does not cut it. I am still seeing that message.

I think you can remove line 1493
    mv -f ${abs_top_srcdir}/test_common.sh ${abs_top_builddir}/test_common.sh
Because AC_CONFIG_FILES at line 1446 will generate file "test_common.sh" in the build folder when doing vpath build.

FYI. When doing source-folder build, I got the message below.
mv: `netcdf-c/test_common.sh' and `netcdf-c/test_common.sh' are the same file

**Comment by DennisHeimbigner** [comment]
Are you doing the vpath are you usihng make distcheck to do that?

**Comment by wkliao** [comment]
I am doing vpath build using the master branch and the message appeared at the end of configure command.
```
mv: cannot stat `/homes/wkliao/NetCDF/GIT/WKLIAO/netcdf-c/test_common.sh': No such file or directory
# NetCDF C Configuration Summary
==============================

# General
-------
NetCDF Version:		4.5.1-development
Configured On:		Wed Jun  7 22:31:05 CDT 2017
Host System:		x86_64-unknown-linux-gnu
. . .
```

**Comment by DennisHeimbigner** [comment]
It appears that the code at the top of all of the test cases was changed from
. ${srcdir}/test_common.sh
to
. ../test_common.sh

This means that test_common.sh has to appear at the top directory of the vpath.
The original line only required $srcdir to be properly defined.
Anyway, my guess is that you need to put test_common.sh in the right location.

**Comment by DennisHeimbigner** [comment]
Ward, it looks to me like we have a missing case in our test matrix. We need to ensure
that we at least once test the automake build using make distcheck instead of make check.
This will test the vpath case.

**Comment by WardF** [comment]
Our test matrix builds `cmake`, `make check` and `make distcheck` currently, in each of the docker containers.  So, our vpath case has been checked.  I also haven't been able to duplicate this issue on any of our systems with a vpath build.  @wkliao what flavor of linux are you using?

**Comment by DennisHeimbigner** [comment]
The fact that the specific term vpath is being used makes me think that @wkliao
is not using automake and make distcheck. The problem is that e.g. automake
establishes a bunch of environment variables such as srcdir. Doing a vpath build
without mimicing at least some of what make distcheck does is likely to cause
tests to fail.

**Comment by wkliao** [comment]
I AM using autotools to build netCDF. When I ran make distcheck, the same error did appear.

Please check the following 2 lines in configure.ac.
```
    1446     AC_CONFIG_FILES(test_common.sh:test_common.in)
    1493     mv -f ${abs_top_srcdir}/test_common.sh ${abs_top_builddir}/test_common.sh
```
When doing vpath build (at running configure command), line 1446 will generate file test_common.sh in ${top_builddir}, and line 1493 will move file test_common.sh from ${abs_top_srcdir} to ${abs_top_builddir}.

Line 1493 fails because test_common.sh was created in ${abs_top_builddir}, but not in ${abs_top_srcdir}.

On my system (a redhat linux box), running command "mv -f fileA fileB" when fileA does not exist will spew the following error. Can you check if yours does that as well?
```
% mv fileA fileB
mv: cannot stat `fileA': No such file or directory"
```

I also just now ran configure command (master branch) on my MacBook Pro and got the same errors.

**Comment by wkliao** [comment]
Just to make it clear, below is the list of commands used in my vpath build.
```
% git clone https://github.com/Unidata/netcdf-c.git
% cd netcdf-c
% autoreconf -i
% cd ..
% mkdir build
% cd build
% ../netcdf-c/configure
```

**Comment by WardF** [comment]
I will address this issue but it does appear to be platform specific; the sequence of commands you outline above cause no problem on OSX related to test_common.sh, but do show a race condition related to ncx.c and nc_test/.  Addressing those now and will also remove the `mv` command since it is redundant.

**Comment by DennisHeimbigner** [comment]
I next guess is that the 'mv' in
    mv -f ${abs_top_srcdir}/${abs_top_builddir}/test_common.sh ${abs_top_builddir}/test_common.sh
should instead be these two commands:
    rm -f ${abs_top_builddir}/test_common.sh 
    cp-f ${abs_top_srcdir}/${abs_top_builddir}/test_common.sh ${abs_top_builddir}/test_common.sh
The reason is that there are probably cases that still assume that test_common.sh
is in $srcdir.

also, did you set
EXPORT srcdir= ...

**Comment by WardF** [comment]
@wkliao I've pushed a change up on branch `v4.5.0-release-branch` that passes the set of commands you outline above, as well as passing `make check`, etc.  Will you test that to see if the issue is resolved on your system?

**Comment by WardF** [comment]
Actually wait a minute the branch hasn't pushed yet.

**Comment by WardF** [comment]
There we are. Ok, if you could let me know if this fixes the issue or not, I will continue to address this! Thanks!

**Comment by wkliao** [comment]
Hi, @DennisHeimbigner
I did not set srcdir. I believe srcdir, builddir etc. are variables reserved by automake and we should use them in Makefile.am (they have no effect on configure runs).

Hi @WardF 
Can you try running command "mv fileA fileB" on your mac?
I wonder why you did not see the error: "mv: cannot stat `fileA': No such file or directory""

**Comment by WardF** [comment]
@wkliao That command fails because there is no fileA.  But on my system, through the build process it outlined, there was never a case where it was trying to copy a file that didn't exist.  It is hopefully a moot point now, however, as the move command was removed and the tests should be referencing the test_common.sh file at the root of the builddir, whether that is coincidentally the root srcdir or not.

**Comment by WardF** [comment]
Realized I accidentally killed the window testing `make distcheck` so re-running now to see if it fails.  If it does, it will be because I asserted it was fixed I'm sure.  Will follow up here when it finishes.

**Comment by wkliao** [comment]
Hi @WardF 
I saw only one-line change in nc_test/Makefile.am in #af91d03.
I was expecting some changes to configure.ac.
Please make sure your local changes are pushed to github.

**Comment by wkliao** [comment]
Line 1446 in cofigure.ac implies file does not exist in ${top_srcdir} before running configure command and the file will be generated after running configure into folder ${top_builddir}.
```
    1446     AC_CONFIG_FILES(test_common.sh:test_common.in)
```

So, if test_common.sh does not exist in ${top_srcdir}, then your mv command should have failed when doing a vpath build.

Please note all my posts are about the outcome of running command "configure". They have not reached to running "make".

**Comment by WardF** [comment]
I understand that this is the result of trying to copy a file that doesn't exist at the end of configure, and I can see why it is failing. I can't explain why it isn't throwing an error on any system I have access to, using a freshly checked out copy, but nevertheless that's what is occurring. It's a moot point, I've pushed some changes that remove the copy as it is unnecessary whether it works or not, and also resolves some race conditions I discovered when make distcheck was run without running make first.

**Comment by DennisHeimbigner** [comment]
That sounds right. If memory serves, the reason I originally used the 'sed' command
was to ensure that test_common.sh was created in srcdir. The change to using
AC_CONFIG_FILES may have altered this and so test_common.sh was never created in srcdir.
but rather in $builddir.  The problem with that statement is that test_common.sh should never
have appeared in srcdir, so the mv should have always failed. So, perhaps it did fail but
was ignored.

So, I went back and looked at the output from the last 4.5 build on travis, and I found this line:
mv: cannot stat '/home/tester/netcdf-c/netcdf-4.5.1-development/test_common.sh': No such file or directory
So the 'mv'; has failed for us as well,  but it was ignored and since test_common.sh
was in builddir, everything worked ok.

**Comment by WardF** [comment]
Let me know if the latest push on the4.5.0 release branch works for you and I'll close out the issue :)

**Comment by wkliao** [comment]
My understanding of autoconf is one should use AC_MSG_ERROR to terminate a fatal error. There are many command-line errors produced in configure file on purpose for various testings, but to let the shell capture a fatal error, one must call exit (which is not in your case).

**Comment by DennisHeimbigner** [comment]
Agreed. We did not consider all the possible consequences of converting from using sed
to using AC_CONFIG_FILES. In any case, I would expect Ward's fix (removing the mv)
to take care of the problem. I assume you will or have independently tested  it by editing
your configure.ac and remove the 'mv' and see if things start working for you.

**Comment by wkliao** [comment]
I just tested the latest branch v4.5.0-release-branch and the error message from mv was gone.
I believe the issue has been resolved.

**Comment by WardF** [comment]
Fantastic! Closing out for the time being until such time as I discover another edge case.  I will merge the changes from the 4.5.0 branch into master, and they will be in rc2 as well.
