### ISSUE TITLE
Issue with ncdump failing with file on thredds server

### ISSUE THREAD

**Issue by WardF** [Unidata/netcdf-c#899]
> Initially reported in esupport issue UOY-859712

````
make checks fail with the following error message:

FAIL: tst_longremote3.sh

logfile is attached.

Installing anyway, results in a ncdump that is not able to connect 
properly with a thredds:

./ncdump 
http://phy-8.io-warnemuende.de:8080/thredds/dodsC/genus/IOW-THREDDS-genus_exp19_run3_5day_ocean_2017-10-20-16.nc

correct header

NetCDF: Index exceeds dimension bound
Location: file vardata.c; line 473

The same works with earlier netcdf builds, build with the same configure 
flags. The server is public.

The result of ldd ncdump looks like for earlier builds.
````

I've confirmed that the `ncdump` command above works in version `v4.4.1.1` but fails starting with `v4.5.0`.

**Comment by WardF** [comment]
Note, `nccopy` reports a size format constraint even in version `4.4.1.1`, so it's possible that there isn't new bug in later versions, but rather the format constraint is being enforced, which seems reasonable.

**Comment by WardF** [comment]
`./ncdump -k http://phy-8.io-warnemuende.de:8080/thredds/dodsC/genus/IOW-THREDDS-genus_exp19_run3_5day_ocean_2017-10-20-16.nc` reports that it is a `classic` file, but the metadata from `./ncdump -h` shows chunksizes, which suggests it is an enhanced data file format.  @DennisHeimbigner could this be something going on in the thredds server?

**Comment by bzfbmsch** [comment]
It's my thredds. The files are MOM output (netcdf3, large file support) deflated like
nccopy -k 3 -d 3 $ncfile ${ncfile}4
Chunking is added during this step. The thredds does simple aggregation over a time axis. 
If more information is needed, please let me know.

**Comment by bzfbmsch** [comment]
bzfbmsch is Martin Schmidt

**Comment by DennisHeimbigner** [comment]
My guess is that there is a problem either with the underlying .dds
or with my libdap2 translation to netcdf-3. The info I am trying to isolate
is which variable is causing the problem.

**Comment by DennisHeimbigner** [comment]
Ok,, at least one of the variables causing the problem is lap_fric_u

**Comment by DennisHeimbigner** [comment]
ok, the problem is that lap_fric_u (and maybe other variables)
are failing the test libsrc/var.c#NC_var_shape.

Not sure if/when this was changed. It claims that it should pass
if dimension cross product is less than X_INT64_MAX -3,
which is appears to be. My speculation is that the code changed
at some point.

Ward- can we do a blame to find out when this was changed (if it was)?


and the max allowed is

**Comment by bzfbmsch** [comment]
netcdf 4.6.0: accessing the files directly works well, through the thredds not
netcdf 4.4.1.1: both access methods work fine.

**Comment by DennisHeimbigner** [comment]
The function that is actually failing is NC_check_vlen, not NC_var_shape.
But the reason, I think, is because of this warning during compilation.
```````````````````
var.c: In function 'NC_var_shape':
ncx.h:107:21: warning: large integer implicitly truncated to unsigned type [-Woverflow]
 #define X_INT64_MAX 9223372036854775807LL
                     ^
var.c:481:34: note: in expansion of macro 'X_INT64_MAX'
     if (0 == NC_check_vlen(varp, X_INT64_MAX-3))
                                  ^~~~~~~~~~~
````````````````````````````
Because of this,, the value passed to NC_check_vlen is 4294967292
instead of 9223372036854775807LL
The proximate reason is that apparently the vlen_max argument
of NC_check_vlen is unsigned int rather than unsigned long long.
So, at some point, i assume that one of us (probably accidentally)
modified the vlen_max argument or we decided to pass X_UINT64_MAX
to that function when it was something else before.
My guess: this has something to do with cdf5 changes.

**Comment by WardF** [comment]
Note that the error in nccopy exists pre-cdf5, in version 4.4.1.1, even though ncdump continues to fail. I can try to sort out when the ncdump behavior changed with git bisect, no problem. I’ll follow up with results shortly.

**Comment by DennisHeimbigner** [comment]
Ok. The bug would not show up unless some one had a very large array,
so it may have been there a while and someone just found it.

**Comment by WardF** [comment]
> It's my thredds. The files are MOM output (netcdf3, large file support) deflated like
> nccopy -k 3 -d 3 $ncfile ${ncfile}4
> Chunking is added during this step. The thredds does simple aggregation over a time axis.
> If more information is needed, please let me know.

I believe the bug is a bit more complicated; chunking and compression are features for netCDF4 files, not netCDF3 classic files.  nccopy appears to be creating netCDF4 files, but with a netCDF3 header block.  This explains the error we are seeing, related to data too large for the file type.  It is also supported by the fact that `ncdump -k http://phy-8.io-warnemuende.de:8080/thredds/dodsC/genus/IOW-THREDDS-genus_exp19_run3_5day_ocean_2017-10-20-16.nc` returns 'classic'.  

@bzfbmsch Instead of passing the `-3` argument to `nccopy`, can you pass `-4`, and see if this issue persists?  I think that nccopy has been correct all along, insofar as saying 'we can't copy this file because it is not a valid netcdf3 file', and the error was that ncdump would a netcdf3-identified file with netcdf4 characteristics properly.

I've tried to download the file to work with it locally, but given the size, this has proven impractical (so far).  

@DennisHeimbigner have I misinterpreted or otherwise made a mistake with my thoughts above?

**Comment by WardF** [comment]
My mistake, I conflated `-3` with `-k 3`.  In any event, running `ncdump -k` against the file in question returns that it is a `classic` file, not a netcdf4 file.  This is the root of the trouble I believe.  I expect if it were a netcdf4 file, the size constraint would not be checked for.

**Comment by DennisHeimbigner** [comment]
When you say "the file", to which one are you referring: the input file ${ncfile}
or the output file ${ncfile}4 ?

**Comment by bzfbmsch** [comment]
Thanks for taking the time. Please remember, the thread starts with a test-failure, 
FAIL: tst_longremote3.sh. 
My example with phy-8 was added to show that this is most probably a real problem.
Unfortunately the original files of the model output are gone, the project is huge.  So I cannot apply nccopy again to the original model output. The data set is an aggregation, a single file has size of about 4GB. I have found another smaller dataset with the same problem. I am running nccopy again like
   nccopy -4 -d2 $dir/ocean_day.nc4 $dir/ocean_day.nc4_repack
 
This takes some time ...

Applying ncdump to a single file of the dataset in question gives:
>ncdump -k ocean_day.nc4 
netCDF-4
Please note, I generated the files with nccopy -k3 not with -3. 
There is another minor difference, when accessing the thredds with ncdump: 
ncdump (4.4.1.1) gives "classic" followed by a newline
ncdump (4.6.0) gives "classic" without a newline 

The same is seen, when applying ncdump directly to the single files, "netCDF-4" is returned with and without a newline. Inspecting files on oceanwatch show the same missing newline with 4.6.0.

Here, is the definition in the thredds-catalog, just to have complete information
  <dataset name="South ..." ID="IOW-THREDDS..." urlPath="genus/IOW-THREDDS...">
     <serviceName>all</serviceName>
     <dataType>Grid</dataType>
     <netcdf xmlns="http://www.unidata.ucar.edu/namespaces/netcdf/ncml-2.2" >         
             <attribute name="Metadata_Conventions" value="Unidata Dataset Discovery v1.0"/>
.... many attributes removed here 
       <aggregation dimName="time" type="joinExisting" >
         <scan location="/atlantic_genus_19/workdir_3" suffix="RUN*/ocean_day.nc4" subdirs="true"/>
          <variable name="u" orgName="u">
             <attribute name="long_name" value="zonal velocity"/>
          </variable>         
          <variable name="v" orgName="v">
             <attribute name="long_name" value="meridional velocity"/>
          </variable>         
          <variable name="st_ocean" orgName="st_ocean">
             <attribute name="standard_name" value="depth"/>
          </variable>         
          <remove type="variable" name="geolon_t"/>
          <remove type="variable" name="geolat_t"/>
          <remove type="variable" name="geolon_c"/>
          <remove type="variable" name="geolat_c"/>       
       </aggregation>
     </netcdf>

**Comment by bzfbmsch** [comment]
oops - the thredds catalog file disappeared. If this information if of some help, I send it via e-mail.

**Comment by DennisHeimbigner** [comment]
I believe I found the problem in the comment above
https://github.com/Unidata/netcdf-c/issues/899#issuecomment-371966748
It remains for us to fix it.

**Comment by bzfbmsch** [comment]
To complete the discussion:
I have packed a dataset again. Unfortunately my choice was not the best, not big enough to show the error.
The single files are recognised by ncdump -k as netCDF-4. Access to the aggregated dataset via thredds returns classic. Seems to be a feature of the thredds server.

**Comment by WardF** [comment]
Thank you @bzfbmsch, we will try to sort this out on our end.  @DennisHeimbigner I'm less familiar with thredds, is there a reason it might be identifying the netCDF-4 files as a classic file? Is it a configuration issue possibly?

**Comment by DennisHeimbigner** [comment]
> Access to the aggregated dataset via thredds returns classic.
I do not know what this means. Can you tell me the set of commands you
used to determine that thredds is returning classic?

**Comment by WardF** [comment]
For my part, I see it as follows:

> ncdump -k http://phy-8.io-warnemuende.de:8080/thredds/dodsC/genus/IOW-THREDDS-genus_exp19_run3_5day_ocean_2017-10-20-16.nc 

returns 'classic'.

**Comment by DennisHeimbigner** [comment]
Remember, thredds is returning DAP2, not netcdf-3. It is the netcdf-c library
that is doing the conversion. Remember also that all DAP2 requests are converted
to netcdf-3. If you want to convert to netcdf-4, then you need to use DAP4.
So, the fact that 
> ncdump -k http://phy-8.io-warnemuende.de:8080/thredds/dodsC/genus/IOW-THREDDS-genus_exp19_run3_5day_ocean_2017-10-20-16.nc

returns classic is exactly what is expected.

**Comment by WardF** [comment]
Excellent information; I didn't realize that.  Is there a way to use DAP4 from clientside, or is that a server-side setting?

**Comment by DennisHeimbigner** [comment]
Depends on whether dap4 is enabled for that server and that dataset on that server.
The client can check this by looking at the catalog entry for that dataset on the server.

**Comment by DennisHeimbigner** [comment]
Fixed by pr https://github.com/Unidata/netcdf-c/pull/904

**Comment by DennisHeimbigner** [comment]
As noted above, this was just recently fixed by pr
https://github.com/Unidata/netcdf-c/pull/904
Remember that it will take some time to propagate
into the official release.

If you need it immediately, I suggest the following:
Either pull the related branch and use that, or
alternately, go to the pull request page, click the "Files Changed"
tab near the top and apply the changes shown there to your
local copy. Then rebuild. In either case, please report here if
it fails to fix your problem.

**Comment by bzfbmsch** [comment]
I downloaded version 4.6.1 and changed the files according to "Files Changed" of #904. I do not have a file "cf" but I think this is not related to my problems. But, the errors still persist:
FAIL: tst_longremote3.sh from the test suite
and the ncdump error on the huge data set hosted on the thredds phy-8:
NetCDF: Index exceeds dimension bound
Location: file vardata.c; line 473
 xu_ocean = 

Since the errors are resolved at your side,  I think I will be patient and wait for the next official release. If I can contribute with more information, local tests etc, please let me know.

**Comment by DennisHeimbigner** [comment]
You can ignore cf; that is for internal debugging.
So, when I ran "ncdump -h" on the file two files I had, namely
LGM_R20C2_detr_MIROC3.2_hdx_tmin_cropped.nc
and
LGM_R20C2_detr_MIROC3.2_hdx_wethat_cropped.nc
It worked successfully. Do you still have those files
and do they fail with ncdump?

It is possible that in fixing this problem, I uncovered a second one.
I will investigate.

**Comment by bzfbmsch** [comment]
Seems, some threads become mixed?

LGM_R20C2_detr_MIROC3.2_hdx_tmin_cropped.nc

thats not one of my files. Searching the web it seems it is part of 
another thread?

My orininal thread was #899, the failure of tst_longremote3.sh.
Possibly related to this, not sure, I reported failing
ncdump 
http://phy-8.io-warnemuende.de:8080/thredds/dodsC/genus/IOW-THREDDS-genus_exp19_run3_5day_ocean_2017-10-20-16.nc

NetCDF: Index exceeds dimension bound

These errors persist with my fileset.

Please let me know, if I can download the files LGM....nc from 
somewhere. So I could check, if ncdump -h works well on these files with 
my newly compiled binary.
Best, Martin

**Comment by DennisHeimbigner** [comment]
My bad. I did get the streams crossed :-)

**Comment by DennisHeimbigner** [comment]
I rechecked. As far as I can tell pull request https://github.com/Unidata/netcdf-c/pull/904
fixes this problem.
